### ISSUE TITLE
Does not Work with Server 2.2 and UP

### ISSUE THREAD

**Issue by donth8dre** [dimitry-ishenko-casparcg/timer-old#7]
Was able to build and run program but it does not work with CasparCG over 2.2

**Comment by dimitry-ishenko** [comment]
My guess is they've made changes to the OSC protocol. You can make appropriate changes here:

https://github.com/dimitry-ishenko-casparcg/timer/blob/d3734f03dae9a5f55b1dc5b6f86d4575cd2fb834/src/osc_video.cpp#L11-L12

At some point we are planning to upgrade our server and at that point I will update the app.

**Comment by donth8dre** [comment]
Well I wouldnt even know what to up in here.

**Comment by dimitry-ishenko** [comment]
Did you check if it works with server < 2.2?

**Comment by donth8dre** [comment]
No, I only started using CasparCG recently as they added HTML support and a majority of my graphics are severed via HTML.

**Comment by dimitry-ishenko** [comment]
Could you give it a try with eg. 2.1 to make sure your setup is correct?

Once we establish that your setup is fine, I can try to guide you to make it work with 2.2 or 2.3.

**Comment by donth8dre** [comment]
ok hold on

**Comment by dimitry-ishenko** [comment]
According to this:

https://github.com/CasparCG/help/wiki/FFmpeg-Producer#osc-data

there is a minor change that affects file name, but the time should still work.

**Comment by donth8dre** [comment]
Just tried it with 2.1 from NRK and it worked. Tried 2.2 and 2.3 and NO luck. I think I can get away with using 2.1 as the HTML push is from the CLIENT and is executed via the server. SO I think I am in GOOOD hands. If you can UPDATE to work with 2.2 and 2.3 I am sure you will make a LOT of others HAPPY.

**Comment by dimitry-ishenko** [comment]
OK good. I will at some point hopefully soon. Just need to wrap my current project.

**Comment by donth8dre** [comment]
Yeah after further test. My HTML stuff does not work properly.

**Comment by dimitry-ishenko** [comment]
> Yeah after further test. My HTML stuff does not work properly.

What exactly doesn't work?

**Comment by donth8dre** [comment]
https://www.twitch.tv/videos/734636842?t=00h09m00s

> > Yeah after further test. My HTML stuff does not work properly.
> 
> What exactly doesn't work?

**Comment by dimitry-ishenko** [comment]
@donth8dre I've re-written the app and it should work with all versions of CasparCG.
You can find it here: https://github.com/dimitry-ishenko-casparcg/timer.
Can you give it a shot and see if it works for you?

**Comment by dimitry-ishenko** [comment]
Closing for now. Please re-open in the new repo if this is still a problem.
